pipeline {
    agent any
    stages {
        stage('Install dependencies') {
            steps {
                sh 'sudo npm install'
            }
        }
        stage('Test application') {
            steps {
                sh 'sudo npm test'
            }
        }
        stage('Build application') {
            steps {
                sh 'sudo npm run build'
            }
        }
        stage('Deploy') {
            steps { 
                sh 'sudo serve -s build'
            }
        }
    }
}